clc 
clear
clf
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/parkershankin-clarke/Desktop/StationFire/NVT.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/02 20:58:17

%% Import the data
[~, ~, raw] = xlsread('/Users/parkershankin-clarke/Desktop/StationFire/NVT.xlsx','Sheet1');
raw = raw(29:end,2:5);

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) (~isnumeric(x) && ~islogical(x)) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Site = data(:,1);
Summer09 = data(:,2);
Winter17 = data(:,3);
Summer18 = data(:,4);

%% Clear temporary variables
clearvars data raw R;

%% Do something
for i = 1:length(Site)
    if Summer09(i)& Winter17(i) & Summer18(i) ~= 0
        subplot(8,8,i)
        list = [Summer09(i),Winter17(i),Summer18(i)];
        plot(list)
        title(Site(i))
    end
end